name: Run on Dev system
on:
    workflow_dispatch:
    push:
      branches:
        - "*"
    pull_request:
      branches:
        - "Dev"


jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the curret environment
        run: echo "Hello ${GITHUB_REF##*/} environment"

