name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.base.ref == 'Stage' || github.event.pull_request.base.ref == 'Prod')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Instructions
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/Dev' ]]; then
            echo "Running instructions for Dev branch..."
            # Add your specific Dev branch instructions here
          elif [[ ${{ github.ref }} == 'refs/heads/Stage' ]]; then
            echo "Running instructions for Stage branch..."
            # Add your specific Stage branch instructions here
          elif [[ ${{ github.ref }} == 'refs/heads/Prod' ]]; then
            echo "Running instructions for Prod branch..."
            # Add your specific Prod branch instructions here
          else
            echo "Running instructions for branch: ${{ github.ref }}"
            # Add instructions for other branches here
          fi
